version: "3.5"

services:
  ambc:
    build:
      context: "."
      dockerfile: "./images/php/Dockerfile"
      args:
        uid: ${UID}
        serverName: ${APP_URL}
    volumes:
      - ./images/php/ambc:/var/www/html
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_DRIVER: redis
    ports:
      - 80:80
      - 443:443
    depends_on:
      - cache
      - db
    networks:
      backend:
        aliases:
          - ambc-apache

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    volumes:
      - db_data:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        aliases:
          - ambc-database

  cache:
    image: redis:6.0-alpine
    restart: unless-stopped
    tty: true
    networks:
      backend:
        aliases:
          - ambc-redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8000:80"
    restart: unless-stopped
    tty: true
    links:
      - db:db
    depends_on:
      - db
    networks:
      backend:
        aliases:
          - ambc-phpmyadmin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 60s

networks:
  backend:
    name: abmc-network

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
