version: "3.5"

services:
  ambc:
    build:
      context: "."
      dockerfile: "./images/php/Dockerfile"
      args:
        uid: ${UID}
        serverName: ${APP_URL}
    container_name: ambc_api
    volumes:
      - ./images/php/ambc:/var/www/html
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: master_db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_DRIVER: redis
    ports:
      - 80:80
      - 443:443
    depends_on:
      - cache
      - master_db
    networks:
      backend:
        aliases:
          - ambc-apache

  master_db:
    image: mysql:8
    container_name: ambc_master_db
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    volumes:
      - master_db_data:/var/lib/mysql
    env_file:
      - ./images/master_db/mysql.env
    networks:
      backend:
        aliases:
          - ambc-database

  cache:
    image: redis:6.0-alpine
    restart: unless-stopped
    container_name: ambc_cache
    tty: true
    networks:
      backend:
        aliases:
          - ambc-redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ambc_phpmyadmin
    environment:
      PMA_HOST: master_db
      PMA_PORT: 3306
    ports:
      - "8000:80"
    restart: unless-stopped
    tty: true
    links:
      - master_db
    depends_on:
      - master_db
    networks:
      backend:
        aliases:
          - ambc-phpmyadmin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 60s

networks:
  backend:
    name: abmc-network

volumes:
  master_db_data:
    driver: local
  ambc_data:
    driver: local
