version: "3.5"

services:
  ambc:
    build:
      context: "."
      dockerfile: "./images/php/Dockerfile"
      args:
        uid: ${UID}
        serverName: ${APP_URL}
    container_name: ambc_api
    volumes:
      - ./images/php/ambc:/var/www/html
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: master_db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_DRIVER: redis
    ports:
      - 80:80
    depends_on:
      - cache
      - master_db
    networks:
      backend:
        aliases:
          - ambc-apache

  master_db:
    image: mysql:8
    container_name: ambc_master_db
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    volumes:
      - master_db_data:/var/lib/mysql
      - ./images/database/master_db/mysql.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    env_file:
      - ./images/database/master_db/mysql.env
    networks:
      backend:
        aliases:
          - ambc-master-database

  slave_db_1:
    image: mysql:8
    container_name: ambc_slave_db_1
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    volumes:
      - ./images/database/slave_db_1/mysql.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    env_file:
      - ./images/database/slave_db_1/mysql.env
    networks:
      backend:
        aliases:
          - ambc-slave-database-1

  slave_db_2:
    image: mysql:8
    container_name: ambc_slave_db_2
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    volumes:
      - ./images/database/slave_db_2/mysql.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    env_file:
      - ./images/database/slave_db_2/mysql.env
    networks:
      backend:
        aliases:
          - ambc-slave-database-2

  cache:
    image: redis:6.0-alpine
    restart: unless-stopped
    container_name: ambc_cache
    tty: true
    networks:
      backend:
        aliases:
          - ambc-redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ambc_phpmyadmin
    environment:
      PMA_HOST: master_db
      PMA_PORT: 3306
    ports:
      - "8000:80"
    restart: unless-stopped
    tty: true
    links:
      - master_db
    depends_on:
      - master_db
    networks:
      backend:
        aliases:
          - ambc-phpmyadmin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 60s

  prometheus:
    image: prom/prometheus
    container_name: ambc_prometheus
    restart: unless-stopped
    tty: true
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./images/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
      - node-exporter
    ports:
      - "9090:9090"

  grafana: ## 193
    image: grafana/grafana
    container_name: ambc_grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    tty: true
    links:
      - prometheus
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 60s

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: ambc_node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100

  cadvisor:
    image: google/cadvisor:latest
    container_name: ambc_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080

networks:
  backend:
    name: abmc-network

volumes:
  master_db_data:
    driver: local
  ambc_data:
    driver: local
